# Generated by Django 5.2.17 on 2026-09-10 14:36

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En curso"),
                            ("success", "Correcto"),
                            ("partial", "Con fallos"),
                            ("failed", "Error"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "full",
                    models.BooleanField(
                        default=False,
                        help_text="Refrescar todas las cartas, no solo las nuevas",
                    ),
                ),
                ("listed", models.PositiveIntegerField(default=0)),
                ("fetched", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("failed_ids", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        help_text="ID de Bandai TCG+", primary_key=True, serialize=False
                    ),
                ),
                ("card_number", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("text", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "card_set",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "set_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="BT20, SD1, P, EX01…",
                        max_length=16,
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="BT, SD, P, EX, TB, DB…",
                        max_length=8,
                    ),
                ),
                ("set_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "collector_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "card_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "colors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("rarity", models.CharField(blank=True, max_length=64)),
                (
                    "rarity_code",
                    models.CharField(blank=True, db_index=True, max_length=16),
                ),
                ("energy", models.SmallIntegerField(blank=True, null=True)),
                ("color_cost", models.CharField(blank=True, max_length=128)),
                (
                    "color_cost_colors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("combo_energy", models.SmallIntegerField(blank=True, null=True)),
                ("combo_power", models.IntegerField(blank=True, null=True)),
                ("power", models.IntegerField(blank=True, null=True)),
                ("z_energy_cost", models.SmallIntegerField(blank=True, null=True)),
                (
                    "characters",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "special_traits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "eras",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=96),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "keyword_families",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=96),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "regulations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("back_id", models.PositiveIntegerField(blank=True, null=True)),
                ("back_name", models.CharField(blank=True, max_length=255)),
                ("back_text", models.TextField(blank=True)),
                ("back_image_url", models.URLField(blank=True, max_length=500)),
                ("back_power", models.IntegerField(blank=True, null=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="card_config original {nombre: valor}",
                    ),
                ),
                ("back_config", models.JSONField(blank=True, default=dict)),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Respuesta completa de la API",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "series",
                    "set_number",
                    "collector_number",
                    "card_number",
                    "id",
                ],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["colors"], name="card_colors_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["characters"], name="card_characters_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["special_traits"], name="card_traits_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["eras"], name="card_eras_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["keywords"], name="card_keywords_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["keyword_families"], name="card_kwfam_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["regulations"], name="card_regulations_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name"],
                        name="card_name_trgm",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["text"],
                        name="card_text_trgm",
                        opclasses=["gin_trgm_ops"],
                    ),
                    models.Index(fields=["energy"], name="card_energy_idx"),
                    models.Index(fields=["power"], name="card_power_idx"),
                ],
            },
        ),
    ]
