# Generated by Django 5.2.17 on 2026-09-10 16:14

import django.contrib.postgres.indexes
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Rellena los textos normalizados de las cartas ya importadas a partir del JSON original."""
    from cards.parsing import parse_card

    Card = apps.get_model("cards", "Card")
    batch = []
    for card in Card.objects.only("id", "raw").iterator(chunk_size=500):
        if not card.raw:
            continue
        parsed = parse_card(card.raw)
        card.effect_text = parsed["effect_text"]
        card.search_text = parsed["search_text"]
        batch.append(card)
        if len(batch) >= 500:
            Card.objects.bulk_update(batch, ["effect_text", "search_text"])
            batch.clear()
    if batch:
        Card.objects.bulk_update(batch, ["effect_text", "search_text"])


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="effect_text",
            field=models.TextField(
                blank=True, help_text="Texto de ambas caras normalizado"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="search_text",
            field=models.TextField(
                blank=True, help_text="Nombre + número + texto normalizados"
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="card",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["effect_text"],
                name="card_effect_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_text"],
                name="card_search_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
