# Generated by Django 5.2.17 on 2026-09-10 16:34

import json
from collections import defaultdict
from pathlib import Path

from django.db import migrations, models


def load_snapshot(apps, schema_editor):
    """Carga la copia incluida de la lista oficial y marca las cartas ya importadas."""
    path = Path(__file__).resolve().parent.parent / "data" / "banlist_snapshot.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    BanListEntry = apps.get_model("cards", "BanListEntry")
    Card = apps.get_model("cards", "Card")
    BanListEntry.objects.bulk_create([
        BanListEntry(list_updated=data.get("updated", ""), source="snapshot", **e) for e in data["entries"]
    ])
    groups = defaultdict(list)
    for e in data["entries"]:
        groups[(e["status"], e["since"])].append(e["card_number"])
    for (status, since), numbers in groups.items():
        Card.objects.filter(card_number__in=numbers).update(legality=status, legality_since=since)


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_search_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanListEntry",
            fields=[
                (
                    "card_number",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("limited", "Limitada"), ("banned", "Prohibida")],
                        max_length=8,
                    ),
                ),
                ("card_name", models.CharField(blank=True, max_length=255)),
                (
                    "limit",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Copias permitidas (limitadas)"
                    ),
                ),
                (
                    "since",
                    models.CharField(
                        blank=True,
                        help_text="Desde cuándo (Norteamérica/Europa)",
                        max_length=255,
                    ),
                ),
                (
                    "list_updated",
                    models.CharField(
                        blank=True,
                        help_text="'last updated on …' de la web oficial",
                        max_length=64,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="official",
                        help_text="official | snapshot",
                        max_length=16,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Carta prohibida/limitada",
                "verbose_name_plural": "Lista Banned/Limited",
                "ordering": ["status", "card_number"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="legality",
            field=models.CharField(
                choices=[
                    ("legal", "Legal"),
                    ("limited", "Limitada"),
                    ("banned", "Prohibida"),
                ],
                db_index=True,
                default="legal",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="legality_since",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(load_snapshot, migrations.RunPython.noop),
    ]
