# Generated by Django 5.2.17 on 2026-09-10 16:37

from django.db import migrations

FIELDS = ["card_type", "colors", "characters", "special_traits", "eras"]


def renormalize(apps, schema_editor):
    """Unifica mayúsculas/espacios de tipo, personajes, rasgos y eras en las cartas ya importadas."""
    from cards.parsing import parse_card

    Card = apps.get_model("cards", "Card")
    batch = []
    for card in Card.objects.only("id", "raw").iterator(chunk_size=500):
        if not card.raw:
            continue
        parsed = parse_card(card.raw)
        for f in FIELDS:
            setattr(card, f, parsed[f])
        batch.append(card)
        if len(batch) >= 500:
            Card.objects.bulk_update(batch, FIELDS)
            batch.clear()
    if batch:
        Card.objects.bulk_update(batch, FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_banlist"),
    ]

    operations = [
        migrations.RunPython(renormalize, migrations.RunPython.noop),
    ]
