# Generated by Django 5.2.17 on 2026-09-11 10:43

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models

KW_FIELDS = ["keywords", "keyword_families", "keyword_mentions", "timing", "keyword_skills", "keyword_rules"]


def load_and_classify(apps, schema_editor):
    """Carga las keyword skills oficiales (copia local) y reclasifica las cartas ya importadas:
    separa habilidades propias de menciones y asigna los nombres oficiales."""
    from cards.parsing import parse_card
    from cards.skills import Catalog

    catalog = Catalog.from_snapshot()
    KeywordSkill = apps.get_model("cards", "KeywordSkill")
    KeywordSkill.objects.bulk_create([
        KeywordSkill(list_updated="Jul. 22, 2022", source="snapshot", **e) for e in catalog.entries])

    Card = apps.get_model("cards", "Card")
    batch = []
    for card in Card.objects.only("id", "raw").iterator(chunk_size=500):
        if not card.raw:
            continue
        parsed = parse_card(card.raw)
        parsed.update(catalog.assign(parsed["keywords"]))
        for f in KW_FIELDS:
            setattr(card, f, parsed[f])
        batch.append(card)
        if len(batch) >= 500:
            Card.objects.bulk_update(batch, KW_FIELDS)
            batch.clear()
    if batch:
        Card.objects.bulk_update(batch, KW_FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_normalize_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordSkill",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Nombre oficial: 'Over Realm X'",
                        max_length=96,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("timing", "Activate Timing"),
                            ("skill", "Keyword Skills"),
                            ("keyword", "Keywords"),
                        ],
                        max_length=8,
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("list_updated", models.CharField(blank=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        default="official",
                        help_text="official | snapshot",
                        max_length=16,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="keyword_mentions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=96),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="keyword_rules",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="keyword_skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="timing",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(load_and_classify, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="card",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["timing"], name="card_timing_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["keyword_skills"], name="card_kwskills_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["keyword_rules"], name="card_kwrules_gin"
            ),
        ),
    ]
