# Generated by Django 5.2.17 on 2026-09-12 15:20

from django.db import migrations

FIELDS = ["back_id", "back_name", "back_text", "back_image_url", "back_power", "back_config",
          "keywords", "keyword_families", "keyword_mentions", "timing", "keyword_skills",
          "keyword_rules", "effect_text", "search_text"]


def drop_wrong_backs(apps, schema_editor):
    """Quita las 'caras traseras' que en realidad son otra carta distinta (dato erróneo de Bandai)."""
    from cards.parsing import parse_card
    from cards.skills import Catalog

    catalog = Catalog.from_db()
    Card = apps.get_model("cards", "Card")
    batch = []
    for card in Card.objects.exclude(back_id=None).only("id", "raw", "card_number").iterator(chunk_size=500):
        if not card.raw or (card.raw.get("backcard_card_number") or card.card_number) == card.card_number:
            continue
        parsed = parse_card(card.raw)
        parsed.update(catalog.assign(parsed["keywords"]))
        for f in FIELDS:
            setattr(card, f, parsed[f])
        batch.append(card)
    if batch:
        Card.objects.bulk_update(batch, FIELDS)


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_keyword_skills"),
    ]

    operations = [
        migrations.RunPython(drop_wrong_backs, migrations.RunPython.noop),
    ]
